name: "Deploy the Backend"
on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Download changes"
        uses: actions/checkout@v4

      - name: "Copy files to VPS via ssh key"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "."
          target: "/api"
      
      - name: "Install python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      # - name: "Install poetry"
      #   uses: snok/install-poetry@v1
      #   with:
      #     virtualenvs-create: true
      #     virtualenvs-in-project: true

      - name: "Build the Backend via ssh key"
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /api
            pip install poetry
            poetry install
            poetry shell
            gunicorn -w 1 -b 127.0.0.1:5000 app:app
            
